{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Tune GPT2 to generate positive reviews\n",
    "> Optimise GPT2 to produce positive IMDB movie reviews using a BERT sentiment classifier for rewards."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<div style=\"text-align: center\">\n",
    "<img src='images/gpt2_bert_training.png' width='600'>\n",
    "<p style=\"text-align: center;\"> <b>Figure:</b> Experiment setup to tune GPT2. The yellow arrows are outside the scope of this notebook, but the trained models are available through Hugging Face. </p>\n",
    "</div>\n",
    "\n",
    "\n",
    "In this notebook we fine-tune GPT2 (small) to generate positive movie reviews based on the IMDB dataset. The model gets 5 tokens from a real review and is tasked to produce positive continuations. To reward positive continuations we use a BERT classifier to analyse the sentiment of the produced sentences and use the classifier's outputs as rewards signals for PPO training."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Setup experiment"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Import dependencies"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[autoreload of transformers failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.albert failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.auto failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.bart failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.barthez failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.bert failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.bert_generation failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.bert_japanese failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.bertweet failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.blenderbot failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.blenderbot_small failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.camembert failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.convbert failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.ctrl failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.deberta failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.distilbert failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.dpr failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.electra failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.encoder_decoder failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.flaubert failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.fsmt failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.funnel failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.gpt2 failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.herbert failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of tokenizers.models failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 613, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 855, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/tokenizers/models/__init__.py\", line 4, in <module>\n",
      "    Model = models.Model\n",
      "AttributeError: module 'tokenizers.models' has no attribute 'Model'\n",
      "]\n",
      "[autoreload of tokenizers.normalizers failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 613, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 855, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/tokenizers/normalizers/__init__.py\", line 3, in <module>\n",
      "    Normalizer = normalizers.Normalizer\n",
      "AttributeError: module 'tokenizers.normalizers' has no attribute 'Normalizer'\n",
      "]\n",
      "[autoreload of tokenizers.pre_tokenizers failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 613, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 855, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/tokenizers/pre_tokenizers/__init__.py\", line 4, in <module>\n",
      "    PreTokenizer = pre_tokenizers.PreTokenizer\n",
      "AttributeError: module 'tokenizers.pre_tokenizers' has no attribute 'PreTokenizer'\n",
      "]\n",
      "[autoreload of tokenizers.processors failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 613, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 855, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/tokenizers/processors/__init__.py\", line 4, in <module>\n",
      "    PostProcessor = processors.PostProcessor\n",
      "AttributeError: module 'tokenizers.processors' has no attribute 'PostProcessor'\n",
      "]\n",
      "[autoreload of tokenizers.decoders failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 613, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 855, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/tokenizers/decoders/__init__.py\", line 3, in <module>\n",
      "    Decoder = decoders.Decoder\n",
      "AttributeError: module 'tokenizers.decoders' has no attribute 'Decoder'\n",
      "]\n",
      "[autoreload of transformers.tokenization_utils failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 480, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 377, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 329, in update_class\n",
      "    if update_generic(old_obj, new_obj):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 377, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 289, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: get_special_tokens_mask() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of transformers.models.bert.tokenization_bert failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 480, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 377, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 329, in update_class\n",
      "    if update_generic(old_obj, new_obj):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 377, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 289, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: get_special_tokens_mask() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of transformers.models.layoutlm failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.led failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.longformer failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.lxmert failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.marian failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.mbart failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.mmbt failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.mobilebert failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.mpnet failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.t5 failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.t5.tokenization_t5 failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 480, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 377, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 329, in update_class\n",
      "    if update_generic(old_obj, new_obj):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 377, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 289, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: get_special_tokens_mask() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of transformers.models.t5.tokenization_t5_fast failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 480, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 377, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 329, in update_class\n",
      "    if update_generic(old_obj, new_obj):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 377, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 329, in update_class\n",
      "    if update_generic(old_obj, new_obj):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 377, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 289, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: get_special_tokens_mask() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of transformers.models.mt5 failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.openai failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.pegasus failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.phobert failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.prophetnet failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.rag failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.reformer failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.retribert failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.roberta failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.squeezebert failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.tapas failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.transfo_xl failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.wav2vec2 failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.xlm failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.xlm_prophetnet failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.xlm_roberta failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.xlnet failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 455, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/importlib/__init__.py\", line 142, in reload\n",
      "    name = module.__spec__.name\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/transformers/file_utils.py\", line 2689, in __getattr__\n",
      "  [Previous line repeated 4 more times]\n",
      "RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "]\n",
      "[autoreload of transformers.models.auto.modeling_auto failed: Traceback (most recent call last):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 257, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 480, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 377, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 329, in update_class\n",
      "    if update_generic(old_obj, new_obj):\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 377, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 368, in <lambda>\n",
      "    lambda a, b: update_function(a.__func__, b.__func__),\n",
      "  File \"/home/wzm289/miniconda3/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 289, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: from_config() requires a code object with 1 free vars, not 0\n",
      "]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The autoreload extension is already loaded. To reload it, use:\n",
      "  %reload_ext autoreload\n"
     ]
    }
   ],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "import wandb\n",
    "import time\n",
    "import os\n",
    "from tqdm import tqdm\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "tqdm.pandas()\n",
    "\n",
    "from datasets import load_dataset\n",
    "\n",
    "from transformers import GPT2Tokenizer\n",
    "from transformers import AutoModelForSequenceClassification, AutoTokenizer\n",
    "\n",
    "from trl.gpt2 import GPT2HeadWithValueModel, respond_to_batch\n",
    "from trl.ppo import PPOTrainer\n",
    "from trl.core import build_bert_batch_from_txt"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Configuration"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "config = {\n",
    "    \"lm_name\": \"lvwerra/gpt2-imdb\",\n",
    "    \"ref_lm_name\": \"lvwerra/gpt2-imdb\",\n",
    "    \"cls_model_name\": \"lvwerra/distilbert-imdb\",\n",
    "    \"tk_name\": \"gpt2\",\n",
    "    \"steps\": 25600,\n",
    "    \"batch_size\": 256,\n",
    "    \"forward_batch_size\": 16,\n",
    "    \"ppo_epochs\": 4,   \n",
    "    \"txt_in_len\": 5,\n",
    "    \"txt_out_len\": 15,\n",
    "    \"lr\": 1.41e-5,\n",
    "    \"init_kl_coef\":0.2,\n",
    "    \"target\": 6,\n",
    "    \"horizon\":10000,\n",
    "    \"gamma\":1,\n",
    "    \"lam\":0.95,\n",
    "    \"cliprange\": .2,\n",
    "    \"cliprange_value\":.2,\n",
    "    \"vf_coef\":.1, \n",
    "}"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "You can see that we load a GPT2 model called `gpt2_imdb`. This model was additionally fine-tuned on the IMDB dataset for 1 epoch with the huggingface [script](https://github.com/huggingface/transformers/blob/master/examples/run_language_modeling.py) (no special settings). The other parameters are mostly taken from the original paper [\"Fine-Tuning Language Models from Human Preferences\"](\n",
    "https://arxiv.org/pdf/1909.08593.pdf). This model as well as the BERT model is available in the Huggingface model zoo [here](https://huggingface.co/models). The following code should automatically download the models."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Initialize W&B logger\n",
    "We use `wandb`to log all the metrics during training."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: You can find your API key in your browser here: https://wandb.ai/authorize\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Appending key for api.wandb.ai to your netrc file: /home/wzm289/.netrc\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "\n",
       "                    Syncing run <strong><a href=\"https://wandb.ai/zhansu/gpt2-sentiment/runs/2i72vyve\" target=\"_blank\">run-42</a></strong> to <a href=\"https://wandb.ai/zhansu/gpt2-sentiment\" target=\"_blank\">Weights & Biases</a> (<a href=\"https://docs.wandb.com/integrations/jupyter.html\" target=\"_blank\">docs</a>).<br/>\n",
       "\n",
       "                "
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<button onClick=\"this.nextSibling.style.display='block';this.style.display='none';\">Display W&B run</button><iframe src=\"https://wandb.ai/zhansu/gpt2-sentiment/runs/2i72vyve?jupyter=true\" style=\"border:none;width:100%;height:420px;display:none;\"></iframe>"
      ],
      "text/plain": [
       "<wandb.sdk.wandb_run.Run at 0x7fa93ff89310>"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "wandb.init(name='run-42', project='gpt2-sentiment', config=config, )"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Load data and models"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Load IMDB dataset\n",
    "The IMDB dataset contains 50k movie review annotated with \"positive\"/\"negative\" feedback indicating the sentiment.  We load the IMDB dataset into a DataFrame and filter for comments that are at least 500 characters long and take the first 1000 characters of each comment. The first filter we apply to avoid comments that are less than `txt_in_len` token long and the second to avoid tokenizing way more text than we actually need."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "ename": "ImportError",
     "evalue": "IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "\u001b[1;32m/projects/futhark1/data/wzm289/code/trl/nbs/04-gpt2-sentiment-ppo-training.ipynb Cell 14'\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      <a href='vscode-notebook-cell://ssh-remote%2Bfutharkhpa01fl.unicph.domain/projects/futhark1/data/wzm289/code/trl/nbs/04-gpt2-sentiment-ppo-training.ipynb#ch0000013vscode-remote?line=0'>1</a>\u001b[0m \u001b[39m# load imdb with datasets\u001b[39;00m\n\u001b[0;32m----> <a href='vscode-notebook-cell://ssh-remote%2Bfutharkhpa01fl.unicph.domain/projects/futhark1/data/wzm289/code/trl/nbs/04-gpt2-sentiment-ppo-training.ipynb#ch0000013vscode-remote?line=1'>2</a>\u001b[0m ds \u001b[39m=\u001b[39m load_dataset(\u001b[39m'\u001b[39;49m\u001b[39mimdb\u001b[39;49m\u001b[39m'\u001b[39;49m, split\u001b[39m=\u001b[39;49m\u001b[39m'\u001b[39;49m\u001b[39mtrain\u001b[39;49m\u001b[39m'\u001b[39;49m)\n\u001b[1;32m      <a href='vscode-notebook-cell://ssh-remote%2Bfutharkhpa01fl.unicph.domain/projects/futhark1/data/wzm289/code/trl/nbs/04-gpt2-sentiment-ppo-training.ipynb#ch0000013vscode-remote?line=2'>3</a>\u001b[0m ds \u001b[39m=\u001b[39m ds\u001b[39m.\u001b[39mrename_columns({\u001b[39m'\u001b[39m\u001b[39mtext\u001b[39m\u001b[39m'\u001b[39m: \u001b[39m'\u001b[39m\u001b[39mreview\u001b[39m\u001b[39m'\u001b[39m, \u001b[39m'\u001b[39m\u001b[39mlabel\u001b[39m\u001b[39m'\u001b[39m: \u001b[39m'\u001b[39m\u001b[39msentiment\u001b[39m\u001b[39m'\u001b[39m})\n\u001b[1;32m      <a href='vscode-notebook-cell://ssh-remote%2Bfutharkhpa01fl.unicph.domain/projects/futhark1/data/wzm289/code/trl/nbs/04-gpt2-sentiment-ppo-training.ipynb#ch0000013vscode-remote?line=3'>4</a>\u001b[0m ds\u001b[39m.\u001b[39mset_format(\u001b[39m'\u001b[39m\u001b[39mpandas\u001b[39m\u001b[39m'\u001b[39m)\n",
      "File \u001b[0;32m~/miniconda3/lib/python3.9/site-packages/datasets/load.py:1675\u001b[0m, in \u001b[0;36mload_dataset\u001b[0;34m(path, name, data_dir, data_files, split, cache_dir, features, download_config, download_mode, ignore_verifications, keep_in_memory, save_infos, revision, use_auth_token, task, streaming, script_version, **config_kwargs)\u001b[0m\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1671'>1672</a>\u001b[0m ignore_verifications \u001b[39m=\u001b[39m ignore_verifications \u001b[39mor\u001b[39;00m save_infos\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1673'>1674</a>\u001b[0m \u001b[39m# Create a dataset builder\u001b[39;00m\n\u001b[0;32m-> <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1674'>1675</a>\u001b[0m builder_instance \u001b[39m=\u001b[39m load_dataset_builder(\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1675'>1676</a>\u001b[0m     path\u001b[39m=\u001b[39;49mpath,\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1676'>1677</a>\u001b[0m     name\u001b[39m=\u001b[39;49mname,\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1677'>1678</a>\u001b[0m     data_dir\u001b[39m=\u001b[39;49mdata_dir,\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1678'>1679</a>\u001b[0m     data_files\u001b[39m=\u001b[39;49mdata_files,\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1679'>1680</a>\u001b[0m     cache_dir\u001b[39m=\u001b[39;49mcache_dir,\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1680'>1681</a>\u001b[0m     features\u001b[39m=\u001b[39;49mfeatures,\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1681'>1682</a>\u001b[0m     download_config\u001b[39m=\u001b[39;49mdownload_config,\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1682'>1683</a>\u001b[0m     download_mode\u001b[39m=\u001b[39;49mdownload_mode,\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1683'>1684</a>\u001b[0m     revision\u001b[39m=\u001b[39;49mrevision,\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1684'>1685</a>\u001b[0m     use_auth_token\u001b[39m=\u001b[39;49muse_auth_token,\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1685'>1686</a>\u001b[0m     \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mconfig_kwargs,\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1686'>1687</a>\u001b[0m )\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1688'>1689</a>\u001b[0m \u001b[39m# Return iterable dataset in case of streaming\u001b[39;00m\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1689'>1690</a>\u001b[0m \u001b[39mif\u001b[39;00m streaming:\n",
      "File \u001b[0;32m~/miniconda3/lib/python3.9/site-packages/datasets/load.py:1512\u001b[0m, in \u001b[0;36mload_dataset_builder\u001b[0;34m(path, name, data_dir, data_files, cache_dir, features, download_config, download_mode, revision, use_auth_token, script_version, **config_kwargs)\u001b[0m\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1509'>1510</a>\u001b[0m     download_config \u001b[39m=\u001b[39m download_config\u001b[39m.\u001b[39mcopy() \u001b[39mif\u001b[39;00m download_config \u001b[39melse\u001b[39;00m DownloadConfig()\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1510'>1511</a>\u001b[0m     download_config\u001b[39m.\u001b[39muse_auth_token \u001b[39m=\u001b[39m use_auth_token\n\u001b[0;32m-> <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1511'>1512</a>\u001b[0m dataset_module \u001b[39m=\u001b[39m dataset_module_factory(\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1512'>1513</a>\u001b[0m     path, revision\u001b[39m=\u001b[39;49mrevision, download_config\u001b[39m=\u001b[39;49mdownload_config, download_mode\u001b[39m=\u001b[39;49mdownload_mode, data_files\u001b[39m=\u001b[39;49mdata_files\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1513'>1514</a>\u001b[0m )\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1515'>1516</a>\u001b[0m \u001b[39m# Get dataset builder class from the processing script\u001b[39;00m\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1516'>1517</a>\u001b[0m builder_cls \u001b[39m=\u001b[39m import_main_class(dataset_module\u001b[39m.\u001b[39mmodule_path)\n",
      "File \u001b[0;32m~/miniconda3/lib/python3.9/site-packages/datasets/load.py:1203\u001b[0m, in \u001b[0;36mdataset_module_factory\u001b[0;34m(path, revision, download_config, download_mode, force_local_path, dynamic_modules_path, data_files, **download_kwargs)\u001b[0m\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1197'>1198</a>\u001b[0m             \u001b[39mif\u001b[39;00m \u001b[39misinstance\u001b[39m(e1, \u001b[39mFileNotFoundError\u001b[39;00m):\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1198'>1199</a>\u001b[0m                 \u001b[39mraise\u001b[39;00m \u001b[39mFileNotFoundError\u001b[39;00m(\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1199'>1200</a>\u001b[0m                     \u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mCouldn\u001b[39m\u001b[39m'\u001b[39m\u001b[39mt find a dataset script at \u001b[39m\u001b[39m{\u001b[39;00mrelative_to_absolute_path(combined_path)\u001b[39m}\u001b[39;00m\u001b[39m or any data file in the same directory. \u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1200'>1201</a>\u001b[0m                     \u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mCouldn\u001b[39m\u001b[39m'\u001b[39m\u001b[39mt find \u001b[39m\u001b[39m'\u001b[39m\u001b[39m{\u001b[39;00mpath\u001b[39m}\u001b[39;00m\u001b[39m'\u001b[39m\u001b[39m on the Hugging Face Hub either: \u001b[39m\u001b[39m{\u001b[39;00m\u001b[39mtype\u001b[39m(e1)\u001b[39m.\u001b[39m\u001b[39m__name__\u001b[39m\u001b[39m}\u001b[39;00m\u001b[39m: \u001b[39m\u001b[39m{\u001b[39;00me1\u001b[39m}\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1201'>1202</a>\u001b[0m                 ) \u001b[39mfrom\u001b[39;00m \u001b[39mNone\u001b[39m\n\u001b[0;32m-> <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1202'>1203</a>\u001b[0m             \u001b[39mraise\u001b[39;00m e1 \u001b[39mfrom\u001b[39;00m \u001b[39mNone\u001b[39m\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1203'>1204</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1204'>1205</a>\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mFileNotFoundError\u001b[39;00m(\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1205'>1206</a>\u001b[0m         \u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mCouldn\u001b[39m\u001b[39m'\u001b[39m\u001b[39mt find a dataset script at \u001b[39m\u001b[39m{\u001b[39;00mrelative_to_absolute_path(combined_path)\u001b[39m}\u001b[39;00m\u001b[39m or any data file in the same directory.\u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1206'>1207</a>\u001b[0m     )\n",
      "File \u001b[0;32m~/miniconda3/lib/python3.9/site-packages/datasets/load.py:1141\u001b[0m, in \u001b[0;36mdataset_module_factory\u001b[0;34m(path, revision, download_config, download_mode, force_local_path, dynamic_modules_path, data_files, **download_kwargs)\u001b[0m\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1138'>1139</a>\u001b[0m _raise_if_offline_mode_is_enabled()\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1139'>1140</a>\u001b[0m \u001b[39mif\u001b[39;00m path\u001b[39m.\u001b[39mcount(\u001b[39m\"\u001b[39m\u001b[39m/\u001b[39m\u001b[39m\"\u001b[39m) \u001b[39m==\u001b[39m \u001b[39m0\u001b[39m:  \u001b[39m# canonical datasets/metrics: github path\u001b[39;00m\n\u001b[0;32m-> <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1140'>1141</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m CanonicalDatasetModuleFactory(\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1141'>1142</a>\u001b[0m         path,\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1142'>1143</a>\u001b[0m         revision\u001b[39m=\u001b[39;49mrevision,\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1143'>1144</a>\u001b[0m         download_config\u001b[39m=\u001b[39;49mdownload_config,\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1144'>1145</a>\u001b[0m         download_mode\u001b[39m=\u001b[39;49mdownload_mode,\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1145'>1146</a>\u001b[0m         dynamic_modules_path\u001b[39m=\u001b[39;49mdynamic_modules_path,\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1146'>1147</a>\u001b[0m     )\u001b[39m.\u001b[39;49mget_module()\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1147'>1148</a>\u001b[0m \u001b[39melif\u001b[39;00m path\u001b[39m.\u001b[39mcount(\u001b[39m\"\u001b[39m\u001b[39m/\u001b[39m\u001b[39m\"\u001b[39m) \u001b[39m==\u001b[39m \u001b[39m1\u001b[39m:  \u001b[39m# users datasets/metrics: s3 path (hub for datasets and s3 for metrics)\u001b[39;00m\n\u001b[1;32m   <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=1148'>1149</a>\u001b[0m     hf_api \u001b[39m=\u001b[39m HfApi(config\u001b[39m.\u001b[39mHF_ENDPOINT)\n",
      "File \u001b[0;32m~/miniconda3/lib/python3.9/site-packages/datasets/load.py:522\u001b[0m, in \u001b[0;36mCanonicalDatasetModuleFactory.get_module\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=519'>520</a>\u001b[0m revision \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mrevision\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=520'>521</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=521'>522</a>\u001b[0m     local_path \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mdownload_loading_script(revision)\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=522'>523</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mFileNotFoundError\u001b[39;00m:\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=523'>524</a>\u001b[0m     \u001b[39mif\u001b[39;00m revision \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m \u001b[39mor\u001b[39;00m os\u001b[39m.\u001b[39mgetenv(\u001b[39m\"\u001b[39m\u001b[39mHF_SCRIPTS_VERSION\u001b[39m\u001b[39m\"\u001b[39m, \u001b[39mNone\u001b[39;00m) \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n",
      "File \u001b[0;32m~/miniconda3/lib/python3.9/site-packages/datasets/load.py:505\u001b[0m, in \u001b[0;36mCanonicalDatasetModuleFactory.download_loading_script\u001b[0;34m(self, revision)\u001b[0m\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=502'>503</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mdownload_loading_script\u001b[39m(\u001b[39mself\u001b[39m, revision: Optional[\u001b[39mstr\u001b[39m]) \u001b[39m-\u001b[39m\u001b[39m>\u001b[39m \u001b[39mstr\u001b[39m:\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=503'>504</a>\u001b[0m     file_path \u001b[39m=\u001b[39m hf_github_url(path\u001b[39m=\u001b[39m\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mname, name\u001b[39m=\u001b[39m\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mname \u001b[39m+\u001b[39m \u001b[39m\"\u001b[39m\u001b[39m.py\u001b[39m\u001b[39m\"\u001b[39m, revision\u001b[39m=\u001b[39mrevision)\n\u001b[0;32m--> <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/load.py?line=504'>505</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m cached_path(file_path, download_config\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mdownload_config)\n",
      "File \u001b[0;32m~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py:298\u001b[0m, in \u001b[0;36mcached_path\u001b[0;34m(url_or_filename, download_config, **download_kwargs)\u001b[0m\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=293'>294</a>\u001b[0m     url_or_filename \u001b[39m=\u001b[39m \u001b[39mstr\u001b[39m(url_or_filename)\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=295'>296</a>\u001b[0m \u001b[39mif\u001b[39;00m is_remote_url(url_or_filename):\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=296'>297</a>\u001b[0m     \u001b[39m# URL, so get it from the cache (downloading if necessary)\u001b[39;00m\n\u001b[0;32m--> <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=297'>298</a>\u001b[0m     output_path \u001b[39m=\u001b[39m get_from_cache(\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=298'>299</a>\u001b[0m         url_or_filename,\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=299'>300</a>\u001b[0m         cache_dir\u001b[39m=\u001b[39;49mcache_dir,\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=300'>301</a>\u001b[0m         force_download\u001b[39m=\u001b[39;49mdownload_config\u001b[39m.\u001b[39;49mforce_download,\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=301'>302</a>\u001b[0m         proxies\u001b[39m=\u001b[39;49mdownload_config\u001b[39m.\u001b[39;49mproxies,\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=302'>303</a>\u001b[0m         resume_download\u001b[39m=\u001b[39;49mdownload_config\u001b[39m.\u001b[39;49mresume_download,\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=303'>304</a>\u001b[0m         user_agent\u001b[39m=\u001b[39;49mdownload_config\u001b[39m.\u001b[39;49muser_agent,\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=304'>305</a>\u001b[0m         local_files_only\u001b[39m=\u001b[39;49mdownload_config\u001b[39m.\u001b[39;49mlocal_files_only,\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=305'>306</a>\u001b[0m         use_etag\u001b[39m=\u001b[39;49mdownload_config\u001b[39m.\u001b[39;49muse_etag,\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=306'>307</a>\u001b[0m         max_retries\u001b[39m=\u001b[39;49mdownload_config\u001b[39m.\u001b[39;49mmax_retries,\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=307'>308</a>\u001b[0m         use_auth_token\u001b[39m=\u001b[39;49mdownload_config\u001b[39m.\u001b[39;49muse_auth_token,\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=308'>309</a>\u001b[0m         ignore_url_params\u001b[39m=\u001b[39;49mdownload_config\u001b[39m.\u001b[39;49mignore_url_params,\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=309'>310</a>\u001b[0m     )\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=310'>311</a>\u001b[0m \u001b[39melif\u001b[39;00m os\u001b[39m.\u001b[39mpath\u001b[39m.\u001b[39mexists(url_or_filename):\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=311'>312</a>\u001b[0m     \u001b[39m# File, and it exists.\u001b[39;00m\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=312'>313</a>\u001b[0m     output_path \u001b[39m=\u001b[39m url_or_filename\n",
      "File \u001b[0;32m~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py:659\u001b[0m, in \u001b[0;36mget_from_cache\u001b[0;34m(url, cache_dir, force_download, proxies, etag_timeout, resume_download, user_agent, local_files_only, use_etag, max_retries, use_auth_token, ignore_url_params)\u001b[0m\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=656'>657</a>\u001b[0m         ftp_get(url, temp_file)\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=657'>658</a>\u001b[0m     \u001b[39melse\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=658'>659</a>\u001b[0m         http_get(\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=659'>660</a>\u001b[0m             url,\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=660'>661</a>\u001b[0m             temp_file,\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=661'>662</a>\u001b[0m             proxies\u001b[39m=\u001b[39;49mproxies,\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=662'>663</a>\u001b[0m             resume_size\u001b[39m=\u001b[39;49mresume_size,\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=663'>664</a>\u001b[0m             headers\u001b[39m=\u001b[39;49mheaders,\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=664'>665</a>\u001b[0m             cookies\u001b[39m=\u001b[39;49mcookies,\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=665'>666</a>\u001b[0m             max_retries\u001b[39m=\u001b[39;49mmax_retries,\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=666'>667</a>\u001b[0m         )\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=668'>669</a>\u001b[0m logger\u001b[39m.\u001b[39minfo(\u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mstoring \u001b[39m\u001b[39m{\u001b[39;00murl\u001b[39m}\u001b[39;00m\u001b[39m in cache at \u001b[39m\u001b[39m{\u001b[39;00mcache_path\u001b[39m}\u001b[39;00m\u001b[39m\"\u001b[39m)\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=669'>670</a>\u001b[0m shutil\u001b[39m.\u001b[39mmove(temp_file\u001b[39m.\u001b[39mname, cache_path)\n",
      "File \u001b[0;32m~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py:456\u001b[0m, in \u001b[0;36mhttp_get\u001b[0;34m(url, temp_file, proxies, resume_size, headers, cookies, timeout, max_retries)\u001b[0m\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=453'>454</a>\u001b[0m content_length \u001b[39m=\u001b[39m response\u001b[39m.\u001b[39mheaders\u001b[39m.\u001b[39mget(\u001b[39m\"\u001b[39m\u001b[39mContent-Length\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=454'>455</a>\u001b[0m total \u001b[39m=\u001b[39m resume_size \u001b[39m+\u001b[39m \u001b[39mint\u001b[39m(content_length) \u001b[39mif\u001b[39;00m content_length \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m \u001b[39melse\u001b[39;00m \u001b[39mNone\u001b[39;00m\n\u001b[0;32m--> <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=455'>456</a>\u001b[0m progress \u001b[39m=\u001b[39m utils\u001b[39m.\u001b[39;49mtqdm(\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=456'>457</a>\u001b[0m     unit\u001b[39m=\u001b[39;49m\u001b[39m\"\u001b[39;49m\u001b[39mB\u001b[39;49m\u001b[39m\"\u001b[39;49m,\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=457'>458</a>\u001b[0m     unit_scale\u001b[39m=\u001b[39;49m\u001b[39mTrue\u001b[39;49;00m,\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=458'>459</a>\u001b[0m     total\u001b[39m=\u001b[39;49mtotal,\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=459'>460</a>\u001b[0m     initial\u001b[39m=\u001b[39;49mresume_size,\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=460'>461</a>\u001b[0m     desc\u001b[39m=\u001b[39;49m\u001b[39m\"\u001b[39;49m\u001b[39mDownloading\u001b[39;49m\u001b[39m\"\u001b[39;49m,\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=461'>462</a>\u001b[0m     disable\u001b[39m=\u001b[39;49m\u001b[39mbool\u001b[39;49m(logging\u001b[39m.\u001b[39;49mget_verbosity() \u001b[39m==\u001b[39;49m logging\u001b[39m.\u001b[39;49mNOTSET),\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=462'>463</a>\u001b[0m )\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=463'>464</a>\u001b[0m \u001b[39mfor\u001b[39;00m chunk \u001b[39min\u001b[39;00m response\u001b[39m.\u001b[39miter_content(chunk_size\u001b[39m=\u001b[39m\u001b[39m1024\u001b[39m):\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/file_utils.py?line=464'>465</a>\u001b[0m     \u001b[39mif\u001b[39;00m chunk:  \u001b[39m# filter out keep-alive new chunks\u001b[39;00m\n",
      "File \u001b[0;32m~/miniconda3/lib/python3.9/site-packages/datasets/utils/tqdm_utils.py:53\u001b[0m, in \u001b[0;36m_tqdm_cls.__call__\u001b[0;34m(self, *args, **kwargs)\u001b[0m\n\u001b[1;32m     <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/tqdm_utils.py?line=50'>51</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m__call__\u001b[39m(\u001b[39mself\u001b[39m, \u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs):\n\u001b[1;32m     <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/tqdm_utils.py?line=51'>52</a>\u001b[0m     \u001b[39mif\u001b[39;00m _active:\n\u001b[0;32m---> <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/tqdm_utils.py?line=52'>53</a>\u001b[0m         \u001b[39mreturn\u001b[39;00m tqdm_lib\u001b[39m.\u001b[39;49mtqdm(\u001b[39m*\u001b[39;49margs, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n\u001b[1;32m     <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/tqdm_utils.py?line=53'>54</a>\u001b[0m     \u001b[39melse\u001b[39;00m:\n\u001b[1;32m     <a href='file:///~/miniconda3/lib/python3.9/site-packages/datasets/utils/tqdm_utils.py?line=54'>55</a>\u001b[0m         \u001b[39mreturn\u001b[39;00m EmptyTqdm(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n",
      "File \u001b[0;32m~/miniconda3/lib/python3.9/site-packages/tqdm/notebook.py:242\u001b[0m, in \u001b[0;36mtqdm_notebook.__init__\u001b[0;34m(self, *args, **kwargs)\u001b[0m\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/tqdm/notebook.py?line=239'>240</a>\u001b[0m unit_scale \u001b[39m=\u001b[39m \u001b[39m1\u001b[39m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39munit_scale \u001b[39mis\u001b[39;00m \u001b[39mTrue\u001b[39;00m \u001b[39melse\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39munit_scale \u001b[39mor\u001b[39;00m \u001b[39m1\u001b[39m\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/tqdm/notebook.py?line=240'>241</a>\u001b[0m total \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mtotal \u001b[39m*\u001b[39m unit_scale \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mtotal \u001b[39melse\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mtotal\n\u001b[0;32m--> <a href='file:///~/miniconda3/lib/python3.9/site-packages/tqdm/notebook.py?line=241'>242</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mcontainer \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mstatus_printer(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mfp, total, \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mdesc, \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mncols)\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/tqdm/notebook.py?line=242'>243</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mcontainer\u001b[39m.\u001b[39mpbar \u001b[39m=\u001b[39m proxy(\u001b[39mself\u001b[39m)\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/tqdm/notebook.py?line=243'>244</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdisplayed \u001b[39m=\u001b[39m \u001b[39mFalse\u001b[39;00m\n",
      "File \u001b[0;32m~/miniconda3/lib/python3.9/site-packages/tqdm/notebook.py:115\u001b[0m, in \u001b[0;36mtqdm_notebook.status_printer\u001b[0;34m(_, total, desc, ncols)\u001b[0m\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/tqdm/notebook.py?line=105'>106</a>\u001b[0m \u001b[39m# Fallback to text bar if there's no total\u001b[39;00m\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/tqdm/notebook.py?line=106'>107</a>\u001b[0m \u001b[39m# DEPRECATED: replaced with an 'info' style bar\u001b[39;00m\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/tqdm/notebook.py?line=107'>108</a>\u001b[0m \u001b[39m# if not total:\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/tqdm/notebook.py?line=111'>112</a>\u001b[0m \n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/tqdm/notebook.py?line=112'>113</a>\u001b[0m \u001b[39m# Prepare IPython progress bar\u001b[39;00m\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/tqdm/notebook.py?line=113'>114</a>\u001b[0m \u001b[39mif\u001b[39;00m IProgress \u001b[39mis\u001b[39;00m \u001b[39mNone\u001b[39;00m:  \u001b[39m# #187 #451 #558 #872\u001b[39;00m\n\u001b[0;32m--> <a href='file:///~/miniconda3/lib/python3.9/site-packages/tqdm/notebook.py?line=114'>115</a>\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mImportError\u001b[39;00m(\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/tqdm/notebook.py?line=115'>116</a>\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mIProgress not found. Please update jupyter and ipywidgets.\u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/tqdm/notebook.py?line=116'>117</a>\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39m See https://ipywidgets.readthedocs.io/en/stable\u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/tqdm/notebook.py?line=117'>118</a>\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39m/user_install.html\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/tqdm/notebook.py?line=118'>119</a>\u001b[0m \u001b[39mif\u001b[39;00m total:\n\u001b[1;32m    <a href='file:///~/miniconda3/lib/python3.9/site-packages/tqdm/notebook.py?line=119'>120</a>\u001b[0m     pbar \u001b[39m=\u001b[39m IProgress(\u001b[39mmin\u001b[39m\u001b[39m=\u001b[39m\u001b[39m0\u001b[39m, \u001b[39mmax\u001b[39m\u001b[39m=\u001b[39mtotal)\n",
      "\u001b[0;31mImportError\u001b[0m: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html"
     ]
    }
   ],
   "source": [
    "# load imdb with datasets\n",
    "ds = load_dataset('imdb', split='train')\n",
    "ds = ds.rename_columns({'text': 'review', 'label': 'sentiment'})\n",
    "ds.set_format('pandas')\n",
    "df = ds[:]\n",
    "\n",
    "# make sure the comments are long enough\n",
    "df = df.loc[df['review'].str.len() > 500]\n",
    "\n",
    "# make sure comments are not too long\n",
    "df['review'] = df['review'].apply(lambda x: x[:1000])\n",
    "\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Load BERT classifier\n",
    "We load a BERT classifier fine-tuned on the IMDB dataset."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "sentiment_model = AutoModelForSequenceClassification.from_pretrained(config[\"cls_model_name\"])\n",
    "sentiment_tokenizer = AutoTokenizer.from_pretrained(config[\"cls_model_name\"])"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "The model outputs are the logits for the negative and positive class. We will use the logits for positive class as a reward signal for the language model."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "SequenceClassifierOutput(loss=None, logits=tensor([[ 2.3350, -2.7266]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)"
      ]
     },
     "execution_count": null,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "text = 'this movie was really bad!!'\n",
    "output = sentiment_model.forward(**sentiment_tokenizer(text, return_tensors=\"pt\"))\n",
    "output"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'sentiment_model' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m/projects/futhark1/data/wzm289/code/trl/nbs/04-gpt2-sentiment-ppo-training.ipynb Cell 19'\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      <a href='vscode-notebook-cell://ssh-remote%2Bfutharkhpa01fl.unicph.domain/projects/futhark1/data/wzm289/code/trl/nbs/04-gpt2-sentiment-ppo-training.ipynb#ch0000018vscode-remote?line=0'>1</a>\u001b[0m text \u001b[39m=\u001b[39m \u001b[39m'\u001b[39m\u001b[39mthis movie was really good!!\u001b[39m\u001b[39m'\u001b[39m\n\u001b[0;32m----> <a href='vscode-notebook-cell://ssh-remote%2Bfutharkhpa01fl.unicph.domain/projects/futhark1/data/wzm289/code/trl/nbs/04-gpt2-sentiment-ppo-training.ipynb#ch0000018vscode-remote?line=1'>2</a>\u001b[0m output \u001b[39m=\u001b[39m sentiment_model\u001b[39m.\u001b[39mforward(\u001b[39m*\u001b[39m\u001b[39m*\u001b[39msentiment_tokenizer(text, return_tensors\u001b[39m=\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mpt\u001b[39m\u001b[39m\"\u001b[39m))\n\u001b[1;32m      <a href='vscode-notebook-cell://ssh-remote%2Bfutharkhpa01fl.unicph.domain/projects/futhark1/data/wzm289/code/trl/nbs/04-gpt2-sentiment-ppo-training.ipynb#ch0000018vscode-remote?line=2'>3</a>\u001b[0m output\n",
      "\u001b[0;31mNameError\u001b[0m: name 'sentiment_model' is not defined"
     ]
    }
   ],
   "source": [
    "text = 'this movie was really good!!'\n",
    "output = sentiment_model.forward(**sentiment_tokenizer(text, return_tensors=\"pt\"))\n",
    "output"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "The resulting reward signal:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "tensor(2.5570, grad_fn=<SelectBackward0>)"
      ]
     },
     "execution_count": null,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "output.logits[0, 1]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Load pre-trained GPT2 language models"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "We load the GPT2 model with a value head and the tokenizer. We load the model twice; the first model is optimized while the second model serves as a reference to calculate the KL-divergence from the starting point. This serves as an additional reward signal in the PPO training to make sure the optimized model does not deviate too much from the original language model."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "gpt2_model = GPT2HeadWithValueModel.from_pretrained(config['lm_name'])\n",
    "gpt2_model_ref = GPT2HeadWithValueModel.from_pretrained(config['ref_lm_name'])\n",
    "gpt2_tokenizer = GPT2Tokenizer.from_pretrained(config['tk_name'])"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Watch model with wandb\n",
    "This wandb magic logs the gradients and weights of the model during training."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[<wandb.wandb_torch.TorchGraph at 0x168e77c10>]"
      ]
     },
     "execution_count": null,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "wandb.watch(gpt2_model, log='all')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Move models to GPU"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "If `cuda` is available move the computations to the GPU."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "_ = gpt2_model.to(device)\n",
    "_ = sentiment_model.to(device)\n",
    "_ = gpt2_model_ref.to(device)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Tokenize IMDB reviews"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "We tokenize all IMDB in advance to avoid tokenizing twice. In the first step we encode the queries and slice the first `txt_in_len` tokens. In a second step we decode these tokens back to text for later display."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22578/22578 [00:21<00:00, 1054.55it/s]\n"
     ]
    }
   ],
   "source": [
    "df['tokens'] = df['review'].progress_apply(lambda x: gpt2_tokenizer.encode(x, return_tensors=\"pt\").to(device)[0, :config['txt_in_len']])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22578/22578 [00:00<00:00, 93906.80it/s]\n"
     ]
    }
   ],
   "source": [
    "df['query'] = df['tokens'].progress_apply(lambda x: gpt2_tokenizer.decode(x))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Optimize model"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Steps**\n",
    "\n",
    "The training loop consists of the following steps:\n",
    "1. Get a batch of queries\n",
    "2. Get the query responses from the policy\n",
    "3. Join query and responses and tokenize for BERT analysis\n",
    "4. Get sentiments for query/responses from BERT\n",
    "5. Optimize policy with PPO using the (query, response, reward) triplet\n",
    "6. Log all the training statistics\n",
    "\n",
    "**Forward batching**\n",
    "\n",
    "Since the models can be fairly big and we want to rollout large PPO batches this can lead to out-of-memory errors when doing the forward passes for text generation and sentiment analysis. We introduce the parameter `forward_batch_size` to split the forward passes into smaller batches. Although this hurts performance a little this is neglectible compared to the computations of the backward passes when optimizing the model. The same parameter is used in the `PPOTrainer` when doing forward passes. The `batch_size` should multiple of `forward_batch_size`.\n",
    "\n",
    "**Training time**\n",
    "\n",
    "This step takes **~2h** on a P6000 GPU with the above specified settings."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "wandb: Network error (ConnectionError), entering retry loop. See wandb/debug-internal.log for full traceback.\n",
      "wandb: Network error resolved after 1:13:45.556307, resuming normal operation.\n"
     ]
    }
   ],
   "source": [
    "ppo_trainer = PPOTrainer(gpt2_model, gpt2_model_ref, **config)\n",
    "fbs = config['forward_batch_size']\n",
    "\n",
    "for epoch in tqdm(range(int(np.ceil(config[\"steps\"]/config['batch_size'])))):\n",
    "    torch.cuda.empty_cache()\n",
    "    logs = dict()\n",
    "    game_data = dict()\n",
    "    timing = dict()\n",
    "    t0 = time.time()\n",
    "    \n",
    "    #### get a batch from the dataset\n",
    "    df_batch = df.sample(config['batch_size'])\n",
    "    game_data['query'] = df_batch['query'].tolist()\n",
    "    query_tensors = torch.stack(df_batch['tokens'].tolist())\n",
    "    \n",
    "    #### get response from gpt2\n",
    "    t = time.time()\n",
    "    total_length = config['txt_in_len']+config['txt_out_len']\n",
    "    response_tensors = []\n",
    "    for i in range(int(config['batch_size']/fbs)):\n",
    "        response  = respond_to_batch(gpt2_model, query_tensors[i*fbs:(i+1)*fbs],\n",
    "                                     txt_len=config['txt_out_len'])\n",
    "        response_tensors.append(response)\n",
    "    response_tensors = torch.cat(response_tensors)\n",
    "    game_data['response'] = [gpt2_tokenizer.decode(response_tensors[i, :]) for i in range(config['batch_size'])]\n",
    "    timing['time/get_response'] = time.time()-t\n",
    "\n",
    "    #### tokenize text for sentiment analysis\n",
    "    t = time.time()\n",
    "    texts = [q + r for q,r in zip(game_data['query'], game_data['response'])]\n",
    "    sentiment_inputs, attention_masks = build_bert_batch_from_txt(texts, sentiment_tokenizer, device)    \n",
    "    timing['time/build_input_sentiment'] = time.time()-t\n",
    "\n",
    "    #### get sentiment score\n",
    "    t = time.time()\n",
    "    rewards = []\n",
    "    for i in range(int(config['batch_size']/fbs)):\n",
    "        res = sentiment_model.forward(sentiment_inputs[i*fbs:(i+1)*fbs],\n",
    "                                      attention_masks[i*fbs:(i+1)*fbs])[0][:, 1].detach()\n",
    "        rewards.append(res)\n",
    "    rewards = torch.cat(rewards)\n",
    "    timing['time/get_sentiment_preds'] = time.time()-t\n",
    "    \n",
    "    #### Run PPO training \n",
    "    t = time.time()\n",
    "    stats = ppo_trainer.step(query_tensors, response_tensors, rewards)\n",
    "    timing['time/optimization'] = time.time()-t\n",
    "     \n",
    "    #### Log everything\n",
    "    timing['time/epoch'] = time.time()-t0\n",
    "    table_rows = [list(r) for r in zip(game_data['query'], game_data['response'], rewards.cpu().tolist())]\n",
    "    logs.update({'game_log':wandb.Table(\n",
    "        columns=['query', 'response', 'reward'],\n",
    "        rows=table_rows)})\n",
    "    logs.update(timing)\n",
    "    logs.update(stats)\n",
    "    logs['env/reward_mean'] = torch.mean(rewards).cpu().numpy()\n",
    "    logs['env/reward_std'] = torch.std(rewards).cpu().numpy()\n",
    "    logs['env/reward_dist'] = rewards.cpu().numpy()\n",
    "    wandb.log(logs)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Training progress\n",
    "If you are tracking the training progress with Weights&Biases you should see a plot similar to the one below. Check out the interactive sample report on wandb.ai: [link](https://app.wandb.ai/lvwerra/trl-showcase/runs/1jtvxb1m/).\n",
    "\n",
    "<div style=\"text-align: center\">\n",
    "<img src='images/gpt2_tuning_progress.png' width='800'>\n",
    "<p style=\"text-align: center;\"> <b>Figure:</b> Reward mean and distribution evolution during training. </p>\n",
    "</div>\n",
    "\n",
    "One can observe how the model starts to generate more positive outputs after a few optimisation steps.\n",
    "\n",
    "> Note: Investigating the KL-divergence will probably show that at this point the model has not converged to the target KL-divergence, yet. To get there would require longer training or starting with a higher inital coefficient."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Model inspection\n",
    "Let's inspect some examples from the IMDB dataset. We can use `gpt2_model_ref` to compare the tuned model `gpt2_model` against the model before optimisation."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>query</th>\n",
       "      <th>response (before)</th>\n",
       "      <th>response (after)</th>\n",
       "      <th>rewards (before)</th>\n",
       "      <th>rewards (after)</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>That's what the title</td>\n",
       "      <td>said to me. All I had to do was hear one word...</td>\n",
       "      <td>says, and this movie was very good,-I really ...</td>\n",
       "      <td>1.710360</td>\n",
       "      <td>4.207656</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>The female hot numbers on</td>\n",
       "      <td>the Fonda get a saving grace here, you can st...</td>\n",
       "      <td>the DVD are beautiful. The music is extraordi...</td>\n",
       "      <td>1.585194</td>\n",
       "      <td>4.228330</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>In the film Kongwon</td>\n",
       "      <td>(American Truffaut), a snake made of ash fall...</td>\n",
       "      <td>has a funky personality and makes the movies ...</td>\n",
       "      <td>-0.015413</td>\n",
       "      <td>2.537073</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Let's see: what</td>\n",
       "      <td>a blast from start to finish, female and male...</td>\n",
       "      <td>happens on that later?&lt;|endoftext|&gt; This film...</td>\n",
       "      <td>3.278678</td>\n",
       "      <td>4.061680</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Really? Is this necessary</td>\n",
       "      <td>for Sith philosophy combined with missionary ...</td>\n",
       "      <td>? Watched this too, but it's what made it so b...</td>\n",
       "      <td>-2.509291</td>\n",
       "      <td>3.025524</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>During a sleepless night</td>\n",
       "      <td>Keira Knightley has besieged a monastery, tro...</td>\n",
       "      <td>, I found this Parker Bros. film. The acting i...</td>\n",
       "      <td>1.341672</td>\n",
       "      <td>3.933312</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>My wife spotted this film</td>\n",
       "      <td>almost halfway through second grade, and afte...</td>\n",
       "      <td>when I was younger and kept her P-1-her-p-</td>\n",
       "      <td>1.781651</td>\n",
       "      <td>1.456647</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>I love John's work</td>\n",
       "      <td>but I actually have to write language as in w...</td>\n",
       "      <td>and I hereby recommend this film. I am really...</td>\n",
       "      <td>-1.904006</td>\n",
       "      <td>4.159198</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>I's a big struggle</td>\n",
       "      <td>to see anyone who acts in that way. by Jim Th...</td>\n",
       "      <td>, but overall I'm happy with the changes even ...</td>\n",
       "      <td>-1.595925</td>\n",
       "      <td>2.651260</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>i liked this film a</td>\n",
       "      <td>lot Paul Verhoeven The other actor does what ...</td>\n",
       "      <td>lot recipe. It was probably one of the best m...</td>\n",
       "      <td>4.314877</td>\n",
       "      <td>4.346435</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>I'd never seen a</td>\n",
       "      <td>heavier, woodier example of Victorian archite...</td>\n",
       "      <td>film of this caliber, and I think it's wonder...</td>\n",
       "      <td>3.297736</td>\n",
       "      <td>4.158653</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>I have to agree with</td>\n",
       "      <td>most people, that Davis was right after all. ...</td>\n",
       "      <td>this movie, the features in this film are fan...</td>\n",
       "      <td>0.609289</td>\n",
       "      <td>4.207779</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>The only reason I watched</td>\n",
       "      <td>it this soon after was because part of it too...</td>\n",
       "      <td>this movie I really do. It helps a little to ...</td>\n",
       "      <td>-2.684667</td>\n",
       "      <td>-2.928670</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>When I think of a</td>\n",
       "      <td>film directed by two independent directors, c...</td>\n",
       "      <td>movie, or potentially a comedy in an interest...</td>\n",
       "      <td>-1.889202</td>\n",
       "      <td>2.494266</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>So first things first..</td>\n",
       "      <td>blank moment. The montage has the mocking tone...</td>\n",
       "      <td>but first we are really surprised when it sho...</td>\n",
       "      <td>-1.846089</td>\n",
       "      <td>2.433687</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>...this one just isn</td>\n",
       "      <td>'t theretonally. I understand the enterprise a...</td>\n",
       "      <td>'t really in, after seeing it. I just love it ...</td>\n",
       "      <td>-2.095725</td>\n",
       "      <td>4.127057</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                        query  \\\n",
       "0       That's what the title   \n",
       "1   The female hot numbers on   \n",
       "2         In the film Kongwon   \n",
       "3             Let's see: what   \n",
       "4   Really? Is this necessary   \n",
       "5    During a sleepless night   \n",
       "6   My wife spotted this film   \n",
       "7          I love John's work   \n",
       "8          I's a big struggle   \n",
       "9         i liked this film a   \n",
       "10           I'd never seen a   \n",
       "11       I have to agree with   \n",
       "12  The only reason I watched   \n",
       "13          When I think of a   \n",
       "14    So first things first..   \n",
       "15       ...this one just isn   \n",
       "\n",
       "                                    response (before)  \\\n",
       "0    said to me. All I had to do was hear one word...   \n",
       "1    the Fonda get a saving grace here, you can st...   \n",
       "2    (American Truffaut), a snake made of ash fall...   \n",
       "3    a blast from start to finish, female and male...   \n",
       "4    for Sith philosophy combined with missionary ...   \n",
       "5    Keira Knightley has besieged a monastery, tro...   \n",
       "6    almost halfway through second grade, and afte...   \n",
       "7    but I actually have to write language as in w...   \n",
       "8    to see anyone who acts in that way. by Jim Th...   \n",
       "9    lot Paul Verhoeven The other actor does what ...   \n",
       "10   heavier, woodier example of Victorian archite...   \n",
       "11   most people, that Davis was right after all. ...   \n",
       "12   it this soon after was because part of it too...   \n",
       "13   film directed by two independent directors, c...   \n",
       "14  blank moment. The montage has the mocking tone...   \n",
       "15  't theretonally. I understand the enterprise a...   \n",
       "\n",
       "                                     response (after)  rewards (before)  \\\n",
       "0    says, and this movie was very good,-I really ...          1.710360   \n",
       "1    the DVD are beautiful. The music is extraordi...          1.585194   \n",
       "2    has a funky personality and makes the movies ...         -0.015413   \n",
       "3    happens on that later?<|endoftext|> This film...          3.278678   \n",
       "4   ? Watched this too, but it's what made it so b...         -2.509291   \n",
       "5   , I found this Parker Bros. film. The acting i...          1.341672   \n",
       "6          when I was younger and kept her P-1-her-p-          1.781651   \n",
       "7    and I hereby recommend this film. I am really...         -1.904006   \n",
       "8   , but overall I'm happy with the changes even ...         -1.595925   \n",
       "9    lot recipe. It was probably one of the best m...          4.314877   \n",
       "10   film of this caliber, and I think it's wonder...          3.297736   \n",
       "11   this movie, the features in this film are fan...          0.609289   \n",
       "12   this movie I really do. It helps a little to ...         -2.684667   \n",
       "13   movie, or potentially a comedy in an interest...         -1.889202   \n",
       "14   but first we are really surprised when it sho...         -1.846089   \n",
       "15  't really in, after seeing it. I just love it ...         -2.095725   \n",
       "\n",
       "    rewards (after)  \n",
       "0          4.207656  \n",
       "1          4.228330  \n",
       "2          2.537073  \n",
       "3          4.061680  \n",
       "4          3.025524  \n",
       "5          3.933312  \n",
       "6          1.456647  \n",
       "7          4.159198  \n",
       "8          2.651260  \n",
       "9          4.346435  \n",
       "10         4.158653  \n",
       "11         4.207779  \n",
       "12        -2.928670  \n",
       "13         2.494266  \n",
       "14         2.433687  \n",
       "15         4.127057  "
      ]
     },
     "execution_count": null,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#### get a batch from the dataset\n",
    "bs = 16\n",
    "game_data = dict()\n",
    "df_batch = df.sample(bs)\n",
    "game_data['query'] = df_batch['query'].tolist()\n",
    "query_tensors = torch.stack(df_batch['tokens'].tolist())\n",
    "\n",
    "#### get response from gpt2 and gpt2_ref\n",
    "total_length = config['txt_in_len']+config['txt_out_len']\n",
    "response_tensors_ref  = respond_to_batch(gpt2_model_ref, query_tensors, txt_len=config['txt_out_len'])\n",
    "game_data['response (before)'] = [gpt2_tokenizer.decode(response_tensors_ref[i, :]) for i in range(bs)]\n",
    "\n",
    "response_tensors  = respond_to_batch(gpt2_model, query_tensors, txt_len=config['txt_out_len'])\n",
    "game_data['response (after)'] = [gpt2_tokenizer.decode(response_tensors[i, :]) for i in range(bs)]\n",
    "\n",
    "#### sentiment analysis of query/response pairs before/after\n",
    "texts = [q + r for q,r in zip(game_data['query'], game_data['response (before)'])]\n",
    "sentiment_inputs, attention_masks = build_bert_batch_from_txt(texts, sentiment_tokenizer, device)    \n",
    "rewards = sentiment_model.forward(sentiment_inputs, attention_masks)[0][:, 1].detach()\n",
    "game_data['rewards (before)'] = rewards.cpu().numpy()\n",
    "\n",
    "texts = [q + r for q,r in zip(game_data['query'], game_data['response (after)'])]\n",
    "sentiment_inputs, attention_masks = build_bert_batch_from_txt(texts, sentiment_tokenizer, device)    \n",
    "rewards = sentiment_model.forward(sentiment_inputs, attention_masks)[0][:, 1].detach()\n",
    "game_data['rewards (after)'] = rewards.cpu().numpy()\n",
    "\n",
    "# store results in a dataframe\n",
    "df_results = pd.DataFrame(game_data)\n",
    "df_results"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Looking at the reward mean/median of the generated sequences we observe a significant difference."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "mean:\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "rewards (before)    0.211196\n",
       "rewards (after)     3.068743\n",
       "dtype: float64"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "median:\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "rewards (before)    0.296938\n",
       "rewards (after)     3.997496\n",
       "dtype: float64"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "print('mean:')\n",
    "display(df_results.mean())\n",
    "print()\n",
    "print('median:')\n",
    "display(df_results.median())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Save model\n",
    "Finally, we save the model to disk for later usage."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "('gpt2-imdb-pos/vocab.json',\n",
       " 'gpt2-imdb-pos/merges.txt',\n",
       " 'gpt2-imdb-pos/special_tokens_map.json',\n",
       " 'gpt2-imdb-pos/added_tokens.json')"
      ]
     },
     "execution_count": null,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "os.makedirs('gpt2-imdb-pos')\n",
    "gpt2_model.save_pretrained('gpt2-imdb-pos')\n",
    "gpt2_tokenizer.save_pretrained('gpt2-imdb-pos')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
